name: Build tag

on:
  push:
    branches:
      - 'master'
      - 'modsecurity'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -t tandrade/ngx:$(echo $([[ $(git rev-parse --abbrev-ref HEAD) == master ]] && echo latest))
    - name: Login
      uses: docker/login-action@v1.10.0
      with:
          username: tandrade
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push
      run: docker push tandrade/ngx:$(git rev-parse --abbrev-ref HEAD)
